//! Onlyne v1.0.0 cluster spec and client configuration.
//!
//! `<server-root>/.onlyne/spec.toml` is the cluster's single source of truth. The
//! file is written by humans and by `onlyne server generate`. This crate parses it
//! strictly, validates it semantically, and reports every rejection with the
//! offending line number.
//!
//! Layout of the crate:
//! * [`spec`] — the document types and the strict loader
//! * [`client`] — `<workspace>/.onlyne/config.toml` with `$NAME` env-indirect values
//! * [`env`] — the read-time environment resolver
//! * [`diff`] — [`SpecDiff`] for the reload answer
//! * [`redact`] — debug strings with secret material masked
//! * [`hash`] — [`spec_hash`] and [`canonical_bytes`] for cache keys
//!
//! The crate depends on nothing else in this workspace. The server maps
//! [`RouteTarget`] into protocol principals.

mod client;
mod diff;
mod env;
mod error;
mod hash;
mod locate;
#[path = "redact.rs"]
mod redact_impl;
mod spec;
pub mod template;

pub use client::{ClientConfig, DEFAULT_STALE_GRACE_SECS, OrcaSection, ServerEndpoint};
pub use diff::{RoleChange, SpecDiff};
pub use env::Env;
pub use error::SpecError;
pub use hash::{canonical_bytes, spec_hash};
pub use redact_impl::SECRET_KEYS;
pub use spec::{
    ACL_EDGE_KINDS, ALLOWED_PLACEHOLDERS, AclEdge, ClientEntry, DEFAULT_AGENT_PACKAGE,
    DEFAULT_BACKOFF_MS, DEFAULT_CERT_PIN_PREFIX, DEFAULT_FAULT_HISTORY_DAYS,
    DEFAULT_HEARTBEAT_TIMEOUT_MS, DEFAULT_INTENT_ATTEMPTS, DEFAULT_KEY_PREFIX,
    DEFAULT_MAX_SESSIONS, DEFAULT_NOTE_QUEUE, DEFAULT_RESYNC_LAG, DEFAULT_STALE_WATCH_SECS,
    DEFAULT_TEMPLATE_ROOT, GatewayEntry, IntentPolicy, KEY_BYTE_LEN, MsgKindClass, RouteEntry,
    RouteTarget, ServerSection, Spec, Timeouts,
};
pub use template::{
    Placeholders, Template, TemplateError, discover, load_tree, local_override, merge_fragment,
    scan_for_prefixes, substitute, substitute_at,
};

/// Root JSON Schema for `spec.toml`, generated by `cargo run -p onlyne-config
/// --bin config-schema` and copied into `OUT_DIR` by `build.rs`.
pub fn spec_schema() -> &'static str {
    include_str!(concat!(env!("OUT_DIR"), "/spec.schema.json"))
}

/// Root JSON Schema for `<workspace>/.onlyne/config.toml`, generated beside
/// [`spec_schema`].
pub fn config_client_schema() -> &'static str {
    include_str!(concat!(env!("OUT_DIR"), "/config-client.schema.json"))
}

pub mod redact {
    //! Debug rendering with secret material masked.
    //!
    //! [`mask`] keeps the first six characters of a value and hides the rest.
    //! [`value`] walks a parsed TOML document, [`spec`] renders a [`Spec`], and
    //! [`client`] renders a [`ClientConfig`] with every environment-resolved value
    //! masked.

    pub use crate::redact_impl::{SECRET_KEYS, client, json, mask, spec, value};
}
