# This file is generated by scripts/render-formula.py on every release.
# Edit the renderer, not this file; the committed copy is the last release's.
class Onlyne < Formula
  desc "Workspace-scoped channel and routing layer for agents"
  homepage "https://github.com/dbydd/onlyne"
  url "https://github.com/dbydd/onlyne/releases/download/v2.1.1/onlyne-2.1.1-aarch64-apple-darwin.tar.gz"
  version "2.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dbydd/onlyne/releases/download/v2.1.1/onlyne-2.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "dfa1605f90610f8ec019fd99009ddffccad27bf3c44613b3bd80e54f8b0243d6"
    end
    on_intel do
      url "https://github.com/dbydd/onlyne/releases/download/v2.1.1/onlyne-2.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "38869590fa016cfca369d9f6fa6b397e0fe5e107f7f5b380560dfecc4baa66b9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dbydd/onlyne/releases/download/v2.1.1/onlyne-2.1.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "ca44c2af81ff1357eae9ba6b180dd7af98a39cc0292b9f31c2f4680fff163632"
    end
    on_intel do
      url "https://github.com/dbydd/onlyne/releases/download/v2.1.1/onlyne-2.1.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6b1c8d4bfcae6ea57745e60f897e8ff8b0d4a4b70c2d0ffefef3d71db8e53465"
    end
  end

  def install
    bin.install "onlyne", "onlyne-server", "onlyne-client"
  end

  test do
    assert_match "onlyne", shell_output("#{bin}/onlyne --help")
  end
end
