# This file is generated by scripts/render-formula.py on every release.
# Edit the renderer, not this file; the committed copy is the last release's.
class Onlyne < Formula
  desc "Workspace-scoped channel and routing layer for agents"
  homepage "https://github.com/dbydd/onlyne"
  url "https://github.com/dbydd/onlyne/releases/download/v2.1.0/onlyne-2.1.0-aarch64-apple-darwin.tar.gz"
  version "2.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dbydd/onlyne/releases/download/v2.1.0/onlyne-2.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "9314763678e20b30d76301b28e0aff85ababb2adfa8699899d268270c0d7ab11"
    end
    on_intel do
      url "https://github.com/dbydd/onlyne/releases/download/v2.1.0/onlyne-2.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "fe91a9845682b5922760d1da7184c14dc657f8340571e62eb9a67d44e07ba1a6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dbydd/onlyne/releases/download/v2.1.0/onlyne-2.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "9c354a8330a1215342b4afc7f93abcd87abccd1db0ff42782e4646348b857a94"
    end
    on_intel do
      url "https://github.com/dbydd/onlyne/releases/download/v2.1.0/onlyne-2.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e719180ad52adb6dc74ab243d2823d2139762af58283c691d5db5eddd9c80610"
    end
  end

  def install
    bin.install "onlyne", "onlyne-server", "onlyne-client"
  end

  test do
    assert_match "onlyne", shell_output("#{bin}/onlyne --help")
  end
end
