# This file is generated by scripts/render-formula.py on every release.
# Edit the renderer, not this file; the committed copy is the last release's.
class Onlyne < Formula
  desc "Workspace-scoped channel and routing layer for agents"
  homepage "https://github.com/dbydd/onlyne"
  url "https://github.com/dbydd/onlyne/releases/download/v2.1.2/onlyne-2.1.2-aarch64-apple-darwin.tar.gz"
  version "2.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dbydd/onlyne/releases/download/v2.1.2/onlyne-2.1.2-aarch64-apple-darwin.tar.gz"
      sha256 "42f3c4cc4f6caa4650adb2619f50a98a27b74ccc63adef5681465ea5894f9aa7"
    end
    on_intel do
      url "https://github.com/dbydd/onlyne/releases/download/v2.1.2/onlyne-2.1.2-x86_64-apple-darwin.tar.gz"
      sha256 "d3c1974d911e348903110387c7781e8e1bccb7a9f141e00a2361c3aa68c7f703"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dbydd/onlyne/releases/download/v2.1.2/onlyne-2.1.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "17242217c1cc7830bf25823038e84af6925b0b39cac3909f29511c3ed37abd69"
    end
    on_intel do
      url "https://github.com/dbydd/onlyne/releases/download/v2.1.2/onlyne-2.1.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "30efe13faf3a91fb48108f932cf87fb3fb9a611792c7d9e590f0f2699dae670a"
    end
  end

  def install
    bin.install "onlyne", "onlyne-server", "onlyne-client"
  end

  test do
    assert_match "onlyne", shell_output("#{bin}/onlyne --help")
  end
end
