#!/usr/bin/env python3
"""Render the Homebrew formula from a release's checksum list.

The formula installs the prebuilt binaries a GitHub Release carries, so its only
per-release facts are the version and the four archive checksums. The release
workflow runs this on every tag and commits the result, which keeps the committed
formula and the published release from drifting.

Usage:
    python3 scripts/render-formula.py --version 1.3.1 \
        --repository dbydd/onlyne --checksums dist/SHA256SUMS \
        --output Formula/onlyne.rb
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# The four targets Homebrew can install. Windows ships in the release and is not
# a brew platform, so it has no row here.
PLATFORMS = [
    ("on_macos", "on_arm", "aarch64-apple-darwin"),
    ("on_macos", "on_intel", "x86_64-apple-darwin"),
    ("on_linux", "on_arm", "aarch64-unknown-linux-gnu"),
    ("on_linux", "on_intel", "x86_64-unknown-linux-gnu"),
]

TEMPLATE = '''# This file is generated by scripts/render-formula.py on every release.
# Edit the renderer, not this file; the committed copy is the last release's.
class Onlyne < Formula
  desc "Workspace-scoped channel and routing layer for agents"
  homepage "https://github.com/{repository}"
  url "https://github.com/{repository}/releases/download/v{version}/onlyne-{version}-aarch64-apple-darwin.tar.gz"
  version "{version}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/{repository}/releases/download/v{version}/onlyne-{version}-aarch64-apple-darwin.tar.gz"
      sha256 "{sha256[aarch64-apple-darwin]}"
    end
    on_intel do
      url "https://github.com/{repository}/releases/download/v{version}/onlyne-{version}-x86_64-apple-darwin.tar.gz"
      sha256 "{sha256[x86_64-apple-darwin]}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/{repository}/releases/download/v{version}/onlyne-{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "{sha256[aarch64-unknown-linux-gnu]}"
    end
    on_intel do
      url "https://github.com/{repository}/releases/download/v{version}/onlyne-{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "{sha256[x86_64-unknown-linux-gnu]}"
    end
  end

  def install
    bin.install "onlyne", "onlyne-server", "onlyne-client", "onlyne-gateway", "onlyne-tui"
  end

  test do
    assert_match "onlyne", shell_output("#{{bin}}/onlyne --help")
  end
end
'''


def checksums(path: Path, version: str) -> dict[str, str]:
    """Map target triple to digest, reading the workflow's own SHA256SUMS.

    An archive is `onlyne-<version>-<target>.<ext>`, and every target carries
    dashes of its own, so the target is what is left after the prefix and the
    extension come off — never what a split on dashes happens to reach.
    """
    out: dict[str, str] = {}
    prefix = f"onlyne-{version}-"
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        digest, _, name = line.partition(" ")
        name = name.rsplit("/", 1)[-1].strip().lstrip("*")
        stem = name.removesuffix(".tar.gz").removesuffix(".zip")
        if not stem.startswith(prefix):
            continue
        out[stem[len(prefix) :]] = digest
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--version", required=True, help="release version without the leading v")
    parser.add_argument("--repository", required=True, help="owner/name")
    parser.add_argument("--checksums", required=True, type=Path, help="SHA256SUMS to read")
    parser.add_argument("--output", required=True, type=Path, help="formula to write")
    args = parser.parse_args()

    found = checksums(args.checksums, args.version)
    missing = [target for _, _, target in PLATFORMS if target not in found]
    if missing:
        print(f"render-formula: no checksum for {', '.join(missing)}", file=sys.stderr)
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        TEMPLATE.format(repository=args.repository, version=args.version, sha256=found)
    )
    print(f"render-formula: wrote {args.output} for {args.version}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
