# This file is generated by scripts/render-formula.py on every release.
# Edit the renderer, not this file; the committed copy is the last release's.
class Onlyne < Formula
  desc "Workspace-scoped channel and routing layer for agents"
  homepage "https://github.com/dbydd/onlyne"
  url "https://github.com/dbydd/onlyne/releases/download/v1.4.1/onlyne-1.4.1-aarch64-apple-darwin.tar.gz"
  version "1.4.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dbydd/onlyne/releases/download/v1.4.1/onlyne-1.4.1-aarch64-apple-darwin.tar.gz"
      sha256 "c839baa179a21f1afa4c05dd8c9b4e94ad9532222e97e05800682c0e85d06882"
    end
    on_intel do
      url "https://github.com/dbydd/onlyne/releases/download/v1.4.1/onlyne-1.4.1-x86_64-apple-darwin.tar.gz"
      sha256 "11e0329c3e8389bf875447125abb27d7133859b7779e7c8eea9987e4b3ac91e0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dbydd/onlyne/releases/download/v1.4.1/onlyne-1.4.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "466b3912c86b6b625595dcb7f2fb9b53f529487b216edfafaad29c431788045d"
    end
    on_intel do
      url "https://github.com/dbydd/onlyne/releases/download/v1.4.1/onlyne-1.4.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "bc76be2be71d7e8353dd29578efdd49f68c3cd3af12ac557d0b216dc6618866f"
    end
  end

  def install
    bin.install "onlyne", "onlyne-server", "onlyne-client", "onlyne-gateway", "onlyne-tui"
  end

  test do
    assert_match "onlyne", shell_output("#{bin}/onlyne --help")
  end
end
